// Demo mode data for testing without Supabase
export const DEMO_USER = {
  id: 'demo-user-001',
  email: 'andrew@demo.com',
  full_name: 'Andrew (Demo)',
  role: 'admin' as const,
  phone: '555-123-4567',
  avatar_url: null,
  created_at: new Date().toISOString(),
  updated_at: new Date().toISOString(),
};

export const DEMO_TEAM_MEMBERS = [
  DEMO_USER,
  {
    id: 'demo-user-002',
    email: 'sarah@demo.com',
    full_name: 'Sarah Johnson',
    role: 'member' as const,
    phone: '555-234-5678',
    avatar_url: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_CONTACTS = [
  {
    id: 'demo-contact-001',
    contact_type: 'buyer',
    first_name: 'John',
    last_name: 'Smith',
    company_name: 'Smith Investments',
    email: 'john@smithinvest.com',
    phone: '555-111-2222',
    phone_secondary: null,
    mailing_address: '123 Main St',
    city: 'Austin',
    state: 'TX',
    zip: '78701',
    counties_of_interest: ['Travis', 'Williamson', 'Hays'],
    states_of_interest: ['TX'],
    min_acreage: 5,
    max_acreage: 50,
    min_price_per_acre: null,
    max_price_per_acre: 15000,
    max_total_budget: 500000,
    preferred_zoning: ['residential', 'agricultural'],
    needs_road_access: true,
    needs_utilities: true,
    needs_water: false,
    preferred_terrain: ['flat', 'rolling'],
    builder_type: null,
    avg_homes_per_year: null,
    preferred_lot_size: null,
    motivation_level: null,
    asking_price: null,
    reason_for_selling: null,
    source: 'referral',
    status: 'active',
    last_contacted_at: new Date().toISOString(),
    assigned_to: 'demo-user-001',
    tags: ['hot-lead', 'cash-buyer'],
    notes: 'Very interested in Williamson County properties',
    created_by: 'demo-user-001',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-contact-002',
    contact_type: 'builder',
    first_name: 'Mike',
    last_name: 'Builder',
    company_name: 'Texas Custom Homes',
    email: 'mike@texascustom.com',
    phone: '555-333-4444',
    phone_secondary: null,
    mailing_address: '456 Builder Lane',
    city: 'Round Rock',
    state: 'TX',
    zip: '78664',
    counties_of_interest: ['Williamson', 'Travis'],
    states_of_interest: ['TX'],
    min_acreage: 0.25,
    max_acreage: 2,
    min_price_per_acre: null,
    max_price_per_acre: 100000,
    max_total_budget: 200000,
    preferred_zoning: ['residential'],
    needs_road_access: true,
    needs_utilities: true,
    needs_water: true,
    preferred_terrain: ['flat'],
    builder_type: 'custom',
    avg_homes_per_year: 12,
    preferred_lot_size: '0.5-1 acre',
    motivation_level: null,
    asking_price: null,
    reason_for_selling: null,
    source: 'website',
    status: 'active',
    last_contacted_at: new Date().toISOString(),
    assigned_to: 'demo-user-001',
    tags: ['repeat-buyer'],
    notes: 'Builds 12 custom homes per year',
    created_by: 'demo-user-001',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_PROPERTIES = [
  {
    id: 'demo-property-001',
    apn: '12345-001',
    address: '1000 Country Road',
    county: 'Williamson',
    state: 'TX',
    zip: '78626',
    latitude: 30.5083,
    longitude: -97.6789,
    legal_description: 'Lot 1, Block A, Country Estates',
    acreage: 10.5,
    zoning: 'agricultural',
    terrain: 'rolling',
    road_access: true,
    road_type: 'paved',
    utilities_available: ['electric', 'water'],
    water_source: 'well',
    flood_zone: 'X',
    hoa: false,
    hoa_fee: null,
    restrictions: 'No mobile homes',
    mineral_rights: true,
    easements: 'Utility easement on north boundary',
    market_value: 180000,
    tax_assessed_value: 150000,
    annual_taxes: 2500,
    purchase_price: 120000,
    purchase_price_per_acre: 11428,
    asking_price: 175000,
    asking_price_per_acre: 16667,
    sold_price: null,
    closing_costs: null,
    profit: null,
    acquisition_date: '2024-01-15',
    listed_date: '2024-02-01',
    sold_date: null,
    status: 'listed_for_sale',
    seller_contact_id: null,
    buyer_contact_id: null,
    assigned_to: 'demo-user-001',
    tags: ['great-views', 'motivated-seller'],
    notes: 'Beautiful hill country views',
    created_by: 'demo-user-001',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_DEALS = [
  {
    id: 'demo-deal-001',
    title: '10 Acres in Williamson County',
    property_id: 'demo-property-001',
    buyer_contact_id: 'demo-contact-001',
    seller_contact_id: null,
    stage: 'negotiating',
    deal_type: 'disposition',
    offer_amount: 160000,
    counter_offer_amount: 170000,
    agreed_price: null,
    earnest_money: 5000,
    due_diligence_fee: 500,
    estimated_profit: 45000,
    commission: null,
    offer_date: '2024-02-10',
    contract_date: null,
    due_diligence_deadline: null,
    closing_date: null,
    actual_close_date: null,
    title_company: 'Austin Title Co',
    title_company_contact: 'Jane Doe',
    title_company_phone: '555-888-9999',
    financing_type: 'cash',
    seller_finance_terms: null,
    contingencies: ['survey', 'title'],
    assigned_to: 'demo-user-001',
    priority: 'high',
    tags: ['hot'],
    notes: 'Buyer very motivated, should close quickly',
    created_by: 'demo-user-001',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-deal-002',
    title: 'New Lead - 5 Acres Travis County',
    property_id: null,
    buyer_contact_id: null,
    seller_contact_id: null,
    stage: 'lead',
    deal_type: 'acquisition',
    offer_amount: null,
    counter_offer_amount: null,
    agreed_price: null,
    earnest_money: null,
    due_diligence_fee: null,
    estimated_profit: 25000,
    commission: null,
    offer_date: null,
    contract_date: null,
    due_diligence_deadline: null,
    closing_date: null,
    actual_close_date: null,
    title_company: null,
    title_company_contact: null,
    title_company_phone: null,
    financing_type: null,
    seller_finance_terms: null,
    contingencies: null,
    assigned_to: 'demo-user-001',
    priority: 'medium',
    tags: [],
    notes: 'Found on Zillow, needs research',
    created_by: 'demo-user-001',
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_TASKS = [
  {
    id: 'demo-task-001',
    title: 'Call John Smith about Williamson property',
    description: 'Follow up on counter offer',
    deal_id: 'demo-deal-001',
    property_id: null,
    contact_id: 'demo-contact-001',
    assigned_to: 'demo-user-001',
    assigned_by: 'demo-user-001',
    status: 'todo',
    priority: 'high',
    due_date: new Date(Date.now() + 86400000).toISOString().split('T')[0], // tomorrow
    completed_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-task-002',
    title: 'Research Travis County property',
    description: 'Check county records and flood maps',
    deal_id: 'demo-deal-002',
    property_id: null,
    contact_id: null,
    assigned_to: 'demo-user-001',
    assigned_by: 'demo-user-001',
    status: 'in_progress',
    priority: 'medium',
    due_date: new Date(Date.now() + 172800000).toISOString().split('T')[0], // 2 days
    completed_at: null,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: 'demo-task-003',
    title: 'Send mailer to seller list',
    description: 'Batch of 500 mailers for Hays County',
    deal_id: null,
    property_id: null,
    contact_id: null,
    assigned_to: 'demo-user-001',
    assigned_by: 'demo-user-001',
    status: 'done',
    priority: 'low',
    due_date: new Date(Date.now() - 86400000).toISOString().split('T')[0], // yesterday
    completed_at: new Date().toISOString(),
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export const DEMO_ACTIVITY_LOG = [
  {
    id: 'demo-activity-001',
    activity_type: 'call',
    subject: 'Called John Smith',
    body: 'Discussed the Williamson County property. He is very interested.',
    outcome: 'interested',
    deal_id: 'demo-deal-001',
    property_id: null,
    contact_id: 'demo-contact-001',
    logged_by: 'demo-user-001',
    created_at: new Date().toISOString(),
  },
  {
    id: 'demo-activity-002',
    activity_type: 'note',
    subject: 'Research completed',
    body: 'Property has clear title, no liens.',
    outcome: null,
    deal_id: 'demo-deal-001',
    property_id: 'demo-property-001',
    contact_id: null,
    logged_by: 'demo-user-001',
    created_at: new Date(Date.now() - 86400000).toISOString(),
  },
];

export const DEMO_INVITATIONS: unknown[] = [];

// Check if we're in demo mode
export function isDemoMode(): boolean {
  if (typeof window !== 'undefined') {
    return localStorage.getItem('demo_mode') === 'true';
  }
  return process.env.NEXT_PUBLIC_SUPABASE_URL?.includes('placeholder') || !process.env.NEXT_PUBLIC_SUPABASE_URL;
}

export function enableDemoMode(): void {
  if (typeof window !== 'undefined') {
    localStorage.setItem('demo_mode', 'true');
  }
}

export function disableDemoMode(): void {
  if (typeof window !== 'undefined') {
    localStorage.removeItem('demo_mode');
  }
}
